name: tropicana_theme
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1


environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
